config/routes.rb
Rails.application.routes.draw do
  root "buildings#index"
  resources :buildings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
    has_many :near_stations, dependent: :destroy
    validates :name, presence: true
    validates :rent, presence: true
    validates :address, presence: true
    validates :age, presence: true
    validates :note, presence: true
    accepts_nested_attributes_for :near_stations, reject_if: :all_blank
end

app/models/near_station.rb
class NearStation < ApplicationRecord
    belongs_to :building
    validates :track_name, presence: true
    validates :station_name, presence: true
    validates :minute_walk, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
    before_action :set_building, only: [:show, :edit, :update, :destroy]
    before_action :set_near_stations, only: [:show, :edit, :update, :destroy]
    def index
        @buildings = Building.all
    end
    def new
        @building = Building.new
        2.times do
            @building.near_stations.build
        end
    end
    def create
        @building = Building.new(building_params)
        if @building.save
            redirect_to buildings_path
        else
            render :new
        end
    end
    def show
    end
    def edit
        2.times do
            @building.near_stations.build
        end
    end
    def update
        if @building.update(building_params)
            redirect_to buildings_path
        else
            render :edit
        end
    end
    def destroy
        @building.destroy
        redirect_to buildings_path
    end
    private
    def building_params
        params.require(:building).permit(
            :name,
            :rent,
            :address,
            :age,
            :note,
            near_stations_attributes: {}
        )
    end
    def set_building
        @building = Building.find(params[:id])
    end
    def set_near_stations
        @near_stations = @building.near_stations
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_form.html.erb
<%= form_with(model: @building, local: true) do |f| %>
    <%= f.label :name, '物件名' %><br>
    <%= f.text_field :name %><br>
    <%= f.label :rent, '賃料' %><br>
    <%= f.text_field :rent %>円<br>
    <%= f.label :address, '住所' %><br>
    <%= f.text_field :address %><br>
    <%= f.label :age, '築年数' %><br>
    <%= f.text_field :age %>年<br>
    <%= f.label :note, '備考' %><br>
    <%= f.text_area :note %><br>
    <hr>
    <% n = 0 %>
    <%= f.fields_for :near_stations do |station_f| %>
        <h4>
            最寄り駅<%= n += 1 %>
        </h4>
        <%= station_f.label :track_name, '路線名' %><br>
        <%= station_f.text_field :track_name %><br>
        <%= station_f.label :station_name, '駅名' %><br>
        <%= station_f.text_field :station_name %><br>
        <%= station_f.label :minute_walk, '徒歩分数' %><br>
        <%= station_f.text_field :minute_walk %>分<br>
    <% end %>
    <%= f.submit '登録する' %>
<% end %>

app/views/buildings/edit.html.erb
<h1>物件編集</h1>
<%= render 'form' %>
<%= link_to '詳細', building_path(@building.id) %> | <%= link_to '戻る', buildings_path %>

app/views/buildings/index.html.erb
<div class="container">
    <h1>物件一覧</h1>
    <table>
        <tr>
            <th>物件名</th>
            <th>賃料</th>
            <th>住所</th>
            <th>築年数</th>
            <th>備考</th>
            <th colspan="3"></th>
        </tr>
        <% @buildings.each do |building| %>
        <tr>
            <td><%= building.name %></td>
            <td><%= building.rent %>円</td>
            <td><%= building.address %></td>
            <td><%= building.age %>年</td>
            <td><%= building.note %></td>
            <td><%= link_to '詳細', building_path(building.id) %></td>
            <td><%= link_to '編集', edit_building_path(building.id) %></td>
            <td><%= link_to '削除', building_path(building.id), method: :delete %></td>
        </tr>
        <% end %>
    </table>
    <br><br>
    <%= link_to '物件を登録する', new_building_path %>
</div>

app/views/buildings/new.html.erb
<h1>物件登録</h1>
<%= render 'form' %>
<%= link_to '戻る', buildings_path %>

app/views/buildings/show.html.erb
<p>
    <span class="bold">物件名：</span>
    <%= @building.name %>
</p>
<p>    
    <span class="bold">賃料：</span>
    <%= @building.rent %>円
</p>
<p>
    <span class="bold">住所：</span>
    <%= @building.address %>
</p>
<p>    
    <span class="bold">築年数</span>
    <%= @building.age %>年
</p>
<p>    
    <span class="bold">備考</span>
    <%= @building.note %>
</p>
<hr>
<% n = 0 %>
<% @near_stations.each do |near_station| %>
    <h4>
        最寄り駅
        <%= n += 1 %>
    </h4>
    <p>
        <span class="bold">路線名</span>
        <%= near_station.track_name%>
    </p>
    <p>
        <span class="bold">駅名</span>
        <%= near_station.station_name%>
    </p>
    <p>
        <span class="bold">徒歩分数</span>
        <%= near_station.minute_walk%>
    </p>
<% end %>
<%= link_to '編集', edit_building_path(@building.id) %> | <%= link_to '戻る', buildings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevExam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>